# Generated by Django 3.0.3 on 2020-02-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='members_pics/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.Member')),
            ],
        ),
    ]
