# Generated by Django 3.0.3 on 2020-02-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200216_1813'),
        ('member_pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpic',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
