# Generated by Django 3.0.3 on 2020-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_pics', '0002_auto_20200216_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpic',
            name='photo',
            field=models.ImageField(upload_to='members_pics/%Y/%m/%d/'),
        ),
    ]
