# Generated by Django 3.0.3 on 2020-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='photo',
            field=models.ImageField(default='default/default.png', upload_to='news-articles/%Y/%m/%d/'),
        ),
    ]
