# Generated by Django 3.0.3 on 2020-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(default='default/default.png', upload_to='gallery/')),
                ('is_banner', models.BooleanField(default=False)),
            ],
        ),
    ]
