# Generated by Django 3.0.3 on 2020-02-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200215_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='default/default.png', upload_to='member/'),
        ),
    ]
