# Generated by Django 3.0.3 on 2020-02-16 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_auto_20200215_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='full_name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.CharField(choices=[('chemical', 'Chemical Engineering'), ('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('mechanical', 'Mechanical Engineering'), ('production', 'Production Engineering')], max_length=25),
        ),
    ]
