# Generated by Django 3.0.3 on 2020-02-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200216_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='display_name',
            new_name='full_name',
        ),
    ]
