# Generated by Django 3.0.3 on 2020-02-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200216_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
