# Generated by Django 3.0.3 on 2020-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='default/default.png', upload_to='member/%Y/%m/%d/'),
        ),
    ]
